version: 0.2

phases:
  install:
    # Runtime env
    runtime-versions:
      java: corretto21
  # Installing dependencies
  pre_build:
    commands:
    - echo "Installing dependencies"
    - mvn install
  # Building docker image
  build:
    commands:
    - echo "Building the docker image..."
    - docker build -t "" .
    - docker push
