version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /cicd-demo/docker/username
    DOCKER_PASSWORD: /cicd-demo/docker/password
    DOCKER_URL: /cicd-demo/docker/docker-registry/url

phases:
  install:
    # Runtime env
    runtime-versions:
      java: corretto21
  # Installing dependencies
  pre_build:
    commands:
    - echo "Installing dependencies"
    - mvn install
  # Building docker image
  build:
    commands:
    - echo "Loggin in docker..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"

    - echo "Building the docker image..."
    - docker build -t "$DOCKER_URL/$DOCKER_USERNAME/weather-app:latest" .

    - echo "Pushing the docker image..."
    - docker push "$DOCKER_URL/$DOCKER_USERNAME/weather-app:latest"
