name: Pipeline with Stages
on: [push]

jobs:
    checkout:
        name: Stage 1 - Repo Checkout
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3
            -   name: Upload Source Code as Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: source-code
                    path: ./

    build:
        strategy:
            matrix: 
                java: ['21', '23']

        name: Stage 2 - Code Building
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            -   name: Setting up Java ${{ matrix.java }}
                uses: actions/setup-java@v4
                with: 
                    java-version: ${{matrix.java}}
                    distribution: 'temurin'
            -   name: Download Source Code Artifact
                uses: actions/download-artifact@v3
                with:
                    name: source-code
            -   name: Build Code
                run: |
                    echo "Building code..."
                    mvn package
            -   name: Upload Build Output as Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: build-output
                    path: build/

    upload:
        name: Stage 3 - Upload Artifact
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Download Build Output Artifact
                uses: actions/download-artifact@v3
                with:
                    name: build-output
            -   name: Finalize Upload Step
                run: echo "Artifact is ready for further use or deployment."